services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    container_name: pgadmin
    depends_on:
      - postgres
    volumes:
      - pgdata:/var/lib/pgadmin/data
    env_file: ".env"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - 8080:8080
volumes:
  pgdata:
networks:
  default:
    name: local-network
    external: true
